name    'CERNOps-activemq'
version '0.1.0'
source 'http://github.com/cernops/activemq'
author 'CERNOps'
license 'Apache License, Version 2.0'
summary 'Configures Apache MQ'
name 'CERNOps-activemq'
version '0.0.1'
summary 'Configures Apache MQ'
description 'Configures Apache MQ'
project_page 'http://github.com/cernops/activemq'
license 'Apache II'
source 'http://github.com/cernops/activemq'
dependency 'richardc/datacat', '>= 0.5.0'
dependency 'puppetlabs/java_ks', '>= 1.2.2'
dependency 'erwbgy/limits', '>= 0.3.1'

